sudo: false
cache: pip

language: python

python:
    - "2.7"
    - "3.6"

matrix:
    include:
        - python: "2.7"
          env: TOXENV=py27
        - python: "3.6"
          env: TOXENV=py36

install:
    - pip install tox

script:
    - tox